# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0002_auto_20170413_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchaseTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
