# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0002_auto_20170402_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ManyToManyField(to='fume.Game')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fume.User')),
            ],
        ),
    ]
