# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0003_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameDescription',
            field=models.TextField(blank=True),
        ),
    ]
