# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0003_purchase_purchasetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchaseTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
