# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fume', '0004_auto_20170413_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchaseTime',
            new_name='pTime',
        ),
    ]
